version: '3.9'
services:
  vue-app:
    build: .
    tty: true
    volumes:
    - ./vueApp:/app
    # command: sh -c "npm install && npm run serve"
    command: sh -c "npm run serve"
    ports:
    - "8080:8080"