version: "3.0"

services:

  api:
    container_name: "security_news_api"
    volumes:
      - ./api:/api
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8000:8000

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    # env_file:
    #   - ../.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: fastapi
    # volumes:
    #   - mongo:/data/db
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
  

# volumes:
#   mongo: