version: "3.0"

services:
  api:
    container_name: "security_news_api"
    volumes:
      - ./api:/api
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - 8080:8080